sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

after_success:
  - ./node_modules/.bin/codecov  -f coverage/coverage-final.json
  - test $TRAVIS_BRANCH = "master" && npm run deploy:gh-pages
  - test $TRAVIS_BRANCH = "lazy-load-routing" && npm run lint

